import Head from "next/head";
import { HeroSection } from "~/components/HeroSection/HeroSection";
import { LogosSection } from "~/components/LogosSection";
import { PageLayout } from "~/layouts/PageLayout";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <HeroSection />
        <LogosSection />
      </PageLayout>
    </>
  );
}
