import Head from "next/head";
import { Gradient } from "~/components/Gradient";
import { HeroSection } from "~/components/HeroSection/HeroSection";
import { PageLayout } from "~/layouts/PageLayout";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gradient />
      <PageLayout>
        <HeroSection />
      </PageLayout>
    </>
  );
}
